# -*- coding: utf-8 -*-
"""Lessons_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Llz28C_u3kdw6g8s0rQtHaPEwFNAyNF2
"""

import math 

class Shape:
  def __init__(self, x, y):
    self.x = x
    self.y = y
  def move(self, delta_x, delta_y):
    self.x = self.x + delta_x
    self.y = self.y + delta_y
#**************************************************** 
class Square(Shape):
  def __init__(self, side=1, x=0, y=0):
    super().__init__(x, y)
    self.side = side

  def get_area(self):
    return self.side * self.side

  def __str__(self):
    return "Square of side %s at coordinates (%d, %d)" % (self.side, self.x, self.y) 
#**************************************************** 

class Triangle(Shape):
  def __init__(self, side=1, x=0, y=0):
    super().__init__(x, y)
    self.side = side

  def get_area(self):
    return math.sqrt(3)/4 * self.side * self.side  

  def __str__(self):
    return "Triangle of side %s at coordinates (%d, %d)" % (self.side, self.x, self.y) 
#****************************************************   
class Circle(Shape):
  pi = 3.14159

  def __init__(self, r=1, x=0, y=0):
    super().__init__(x, y)
    self.radius = r

  def get_area(self):
    return self.radius * self.radius * self.pi

  def __str__(self):
    return "Circle of radius %s at coordinates (%d, %d)" % (self.radius, self.x, self.y)

c1 = Circle(5)
c2 = Circle(5, 15, 20)
print(c1)
print(c2)

print('Circle of Square ', c2.get_area())

a = Square(7)
print('Area of Square ', a.get_area())

b = Triangle(9, 15, 20)
print(b)
b = Triangle(8)

print('Area of Triangle ', b.get_area())
#c.move(3, 4)
#print(c.x, c.y, sep='\n')